// GET PROJECTS
export const PROJECTS_LIST_REQUEST = "PROJECTS_LIST_REQUEST";
export const PROJECTS_LIST_SUCCESS = "PROJECTS_LIST_SUCCESS";
export const PROJECTS_LIST_FAIL = "PROJECTS_LIST_FAIL";

// GET SPECIFIC PROJECT
export const PROJECT_REQUEST = "PROJECT_REQUEST";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAIL = "PROJECT_FAIL";
