// GET subscribers
export const SUBSCRIBERS_LIST_REQUEST = 'SUBSCRIBERS_LIST_REQUEST';
export const SUBSCRIBERS_LIST_SUCCESS = 'SUBSCRIBERS_LIST_SUCCESS';
export const SUBSCRIBERS_LIST_FAIL = 'SUBSCRIBERS_LIST_FAIL';

// REMOVE subscribers from redux
export const SUBSCRIBERS_REMOVE_LIST = 'SUBSCRIBERS_REMOVE_LIST';

// DELETE subscribers
export const SUBSCRIBERS_DELETE_SUCCESS = 'SUBSCRIBERS_DELETE_SUCCESS';
export const SUBSCRIBERS_DELETE_FAIL = 'SUBSCRIBERS_DELETE_FAIL';
