// GET subscribers
export const SUBSCRIBERS_LIST_REQUEST = 'SUBSCRIBERS_LIST_REQUEST';
export const SUBSCRIBERS_LIST_SUCCESS = 'SUBSCRIBERS_LIST_SUCCESS';
export const SUBSCRIBERS_LIST_FAIL = 'SUBSCRIBERS_LIST_FAIL';
// DELETE subscribers
export const SUBSCRIBERS_DELETE_REQUEST = 'SUBSCRIBERS_DELETE_REQUEST';
export const SUBSCRIBERS_DELETE_SUCCESS = 'SUBSCRIBERS_DELETE_SUCCESS';
export const SUBSCRIBERS_DELETE_FAIL = 'SUBSCRIBERS_DELETE_FAIL';
